name: verbum_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.9.0
  firebase_auth:
  cloud_firestore:
  firebase_ai: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: 

flutter:
  uses-material-design: true
  assets:
    - assets/matrix/index.html
    - assets/gifs/matrix.gif
  